name: Release Drafter

on:
  push:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    name: Update Release Draft
    permissions:
      contents: write  # to create and update releases
      pull-requests: read  # to read pull request information
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update release draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}